### ISSUE TITLE
The pretrained 'model_mot_lstm' is not included in Google drive

### ISSUE THREAD

**Issue by Vio1etovo** [MedChaabane/DEFT#14]
like this: model_kitti_lstm.pth、model_kitti.pth
in this link: https://drive.google.com/drive/folders/1dlVoV-4fMYlttdj2ba0unn6WX-nxaC48?usp=sharing

**Comment by Vio1etovo** [comment]
This is an excellent job. But some errors appeared when I ran the code.
After running ‘train.py’, there is an error in ‘train_prediction.py’:
>
Starting training...
Traceback (most recent call last):
  File "/home/zbx/Anaconda3/envs/DEFT-main/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/zbx/Anaconda3/envs/DEFT-main/lib/python3.6/queue.py", line 173, in get
    self.not_empty.wait(remaining)
  File "/home/zbx/Anaconda3/envs/DEFT-main/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
  File "/home/zbx/Anaconda3/envs/DEFT-main/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 29863) is killed by signal: Segmentation fault. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/train_prediction.py", line 133, in <module>
    main(opt)
  File "src/train_prediction.py", line 99, in main
    for iter_id, (inputs, targets) in enumerate(train_loader):
  File "/home/zbx/Anaconda3/envs/DEFT-main/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/zbx/Anaconda3/envs/DEFT-main/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "/home/zbx/Anaconda3/envs/DEFT-main/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 931, in _get_data
    success, data = self._try_get_data()
  File "/home/zbx/Anaconda3/envs/DEFT-main/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 29863) exited unexpectedly
>
After that, I modified batch_sized and num_works to (1, 0)
But there was an error again:
>
Starting training...
Segmentation fault (core dumped)
>
So I don't know how to modify it, please help me, thanks!

**Comment by Vio1etovo** [comment]
This is an excellent job. But some errors appeared when I ran the code.
After running ‘train.py’, there is an error in ‘train_prediction.py’:
'''
Starting training...
Traceback (most recent call last):
  File "/home/zbx/Anaconda3/envs/DEFT-main/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/zbx/Anaconda3/envs/DEFT-main/lib/python3.6/queue.py", line 173, in get
    self.not_empty.wait(remaining)
  File "/home/zbx/Anaconda3/envs/DEFT-main/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
  File "/home/zbx/Anaconda3/envs/DEFT-main/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 29863) is killed by signal: Segmentation fault. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/train_prediction.py", line 133, in <module>
    main(opt)
  File "src/train_prediction.py", line 99, in main
    for iter_id, (inputs, targets) in enumerate(train_loader):
  File "/home/zbx/Anaconda3/envs/DEFT-main/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/zbx/Anaconda3/envs/DEFT-main/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "/home/zbx/Anaconda3/envs/DEFT-main/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 931, in _get_data
    success, data = self._try_get_data()
  File "/home/zbx/Anaconda3/envs/DEFT-main/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 29863) exited unexpectedly
'''
After that, I modified batch_sized and num_works to (1, 0)
But there was an error again:
'''
Starting training...
Segmentation fault (core dumped)
'''
So I don't know how to modify it, please help me, thanks!

**Comment by prabhuiitdhn** [comment]
@Vio1etovo Have you fixed the issue, I am working on converting the model_mot to onnx. I am getting some kind of error. I can write it more If you are okay to help. Thank you.

**Comment by hossammosh** [comment]
why did not chaabane solve it ?
